name: Deploy

on:
  push:
    tags:
      - '*-prod'

# Authenticate to the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # обязательно для тегов

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/superset/
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh "${GITHUB_REF#refs/tags/}"
